export enum ErrorCode {
  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  // Booking
  BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND",
  BOOKING_ALREADY_CANCELLED = "BOOKING_ALREADY_CANCELLED",
  BOOKING_CANCELLATION_WINDOW_EXPIRED = "BOOKING_CANCELLATION_WINDOW_EXPIRED",
  // Payment
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_ALREADY_PROCESSED = "PAYMENT_ALREADY_PROCESSED",
  STRIPE_WEBHOOK_INVALID = "STRIPE_WEBHOOK_INVALID",
  // Inventory
  FLIGHT_NOT_FOUND = "FLIGHT_NOT_FOUND",
  HOTEL_NOT_FOUND = "HOTEL_NOT_FOUND",
  BUNDLE_NOT_FOUND = "BUNDLE_NOT_FOUND",
  PROMOTION_NOT_FOUND = "PROMOTION_NOT_FOUND",
  // External
  AMADEUS_API_ERROR = "AMADEUS_API_ERROR",
  AMADEUS_RATE_LIMIT = "AMADEUS_RATE_LIMIT",
  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_DATE_RANGE = "INVALID_DATE_RANGE",
  BUDGET_TOO_LOW = "BUDGET_TOO_LOW",
  // Generic
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_FOUND = "NOT_FOUND",
}
